# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
