# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webches', '0002_homecontac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeContac',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=datetime.datetime(2017, 4, 11, 15, 5, 56, 282313, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
