# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webches', '0003_auto_20170411_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 11, 15, 14, 1, 483934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
